2024-09-24 22:18:53,213 | WARNING | Неверный тип данных для имени экземпляра Runner
Traceback (most recent call last):
  File "C:\Users\focus\Desktop\PythonProjectsForUniversity1\HomeWork\12-06 Логирование\RunnerTest.py", line 27, in test_run
    runner = task.Runner(2)
             ^^^^^^^^^^^^^^
  File "C:\Users\focus\Desktop\PythonProjectsForUniversity1\HomeWork\12-06 Логирование\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-24 22:18:53,214 | WARNING | Скорость не может быть отрицательной,
Traceback (most recent call last):
  File "C:\Users\focus\Desktop\PythonProjectsForUniversity1\HomeWork\12-06 Логирование\RunnerTest.py", line 12, in test_walk
    r = task.Runner('Вася', -5)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\focus\Desktop\PythonProjectsForUniversity1\HomeWork\12-06 Логирование\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
